global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "java_application"
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      # 로컬 개발 환경 (docker compose --profile full up 사용 시)
      - targets: ["chwimeet-app:8080"]
        labels:
          env: "local"